### PR TITLE
Update Firefox Beta, Developer and Nightly logos (Fixes #30)

### LINKED ISSUE #30: Update pre-release browser logos
As of today's Nightly (2019-08-11) there's a new browser logo. 

image

Protocol should update the [existing Nightly logo](https://github.com/mozilla/protocol-assets/blob/master/logos/firefox/nightly-high-res.png) to match above ^

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@stephaniehobson good spot. The drop-shadow on the new logos doesn't seem to resize well at small sizes. Rather than play around with this, I decided it's probably better just to use some of the pre-exported sizes in the drive folder and update using those.

This means the logo sizes go from 200px -> 256px, and 100px -> 128px, but that's hopefully a minor bump in terms of bytes? I don't have Illustrator installed to play around with this further.

**Comment by stephaniehobson** [comment]
R+ 📐 after the changelog update.

**Comment by alexgibson** [comment]
> I think because the logo sizes have changed this needs a (breaking) warning and a full version bump. Consumers should check that they have defined sizes in their CSS and HTML where they have used existing logos.

Hmm, this is an odd one. I don't think this is likely going to risk breaking someone's build / deployment - but it could potentially make a logo appear slightly larger than usual on a web page, depending on how it's consumed. I'm inclined to say this could be a minor patch bump (adding a slightly larger image size but in a backward compatible way), so we'd bump it to 2.1.0.

Thoughts?

**Comment by stephaniehobson** [comment]
I'm more worried about If it's being used as a CSS background image without a `background-size` declaration with it.

But I don't want to over think this either!

**Pull request merged**
